server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:guesthub;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

jwt:
  secret: ${JWT_SECRET:dev-secret-change-me}
  expiration-minutes: 120

# Allow default CORS handled in SecurityConfig