server:
  port: 8001

spring:
  data:
    mongodb:
      uri: ${MONGO_URL:mongodb://localhost:27017}
      database: ${DB_NAME:guesthub_db}
  application:
    name: guesthub-backend

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.guesthub: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: ${JWT_SECRET:dev-secret-change-me-in-production-environment}
  expiration-minutes: 120

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true